<?php

/**
 * @file
 * KOE
 *
 * Filename:     KOE Theme.
 * Description:  Drupal 9 Template.
 * Author:       Goblin Creative.
 */

use Drupal\Core\Link;
use Drupal\file\Entity\File;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Cmf\Component\Routing\RouteObjectInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

global $base_url;
global $head_title;
global $view;

$theme_path = \Drupal::service('extension.path.resolver')->getPath('theme', 'koecontrato');

/**
 * Implements template_preprocess_html().
 */
function koecontrato_preprocess(&$variables, $hook) {
  $variables['base_path'] = base_path();
}
/**
 * Implements template_preprocess_html().
 */
function koecontrato_preprocess_html(&$variables) {
  $site_config = \Drupal::config('system.site');
  $variables['site_name'] = $site_config->get('name');
  $variables['site_slogan'] = $site_config->get('slogan');
  $variables['logo'] = \Drupal::service('file_url_generator')->generateString(theme_get_setting('logo.url'));
}
/**
 * Implements hook_preprocess_field().
 */
function koecontrato_preprocess_field(&$variables) {
  $site_config = \Drupal::config('system.site');
  $variables['site_name'] = $site_config->get('name');
  $variables['site_slogan'] = $site_config->get('slogan');
  $variables['logo'] = \Drupal::service('file_url_generator')->generateString(theme_get_setting('logo.url'));
}
/**
 * Implements hook_preprocess_node().
 */
function koecontrato_preprocess_node(&$variables) {
  $node = &$variables['node'];
  $node_array = $node->toArray();
}
/**
 * Implements template_preprocess_page().
 */
function koecontrato_preprocess_page(&$variables) {
  $site_config = \Drupal::config('system.site');
  $variables['site_name'] = $site_config->get('name');
  $variables['site_slogan'] = $site_config->get('slogan');
  $variables['logopath'] = '/' . \Drupal::config('koecontrato.settings')->get('logo.path');
}
/**
 * Implements hook_page_attachments_alter().
 */
function koecontrato_page_attachments_alter(&$page) {
  $viewport = [
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => [
      'name' => 'viewport',
      'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no',
    ],
  ];
  $page['#attached']['html_head'][] = [$viewport, 'viewport'];
}
/**
 * Implements template_preprocess_block().
 */
function koecontrato_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'system_branding_block') {
    $variables['attributes']['class'][] = 'clearfix';
    $tmp_logo = theme_get_setting('logo');
    $variables['setting_logo'] = $tmp_logo['use_default'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function koecontrato_preprocess_menu(&$variables) {
  $variables['attributes']['class'][] = 'clearfix';
}
/**
 * Implements hook_theme_suggestions_HOOK_alter() for page 404.
 */
function koecontrato_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  global $base_url;

  $theme_path = \Drupal::service('extension.path.resolver')->getPath('theme', 'koecontrato');
  $variables['theme_path'] = $base_url . '/' . $theme_path;

  $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  $suggestions = theme_get_suggestions($path_args, 'page');
  $http_error_suggestions = [
    'system.401' => 'page__401',
    'system.403' => 'page__403',
    'system.404' => 'page__404',
  ];
  $route_name = \Drupal::routeMatch()->getRouteName();
  if (isset($http_error_suggestions[$route_name])) {
    $suggestions[] = $http_error_suggestions[$route_name];
  }
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK() for maintenance-page.html.twig.
 */
function koecontrato_preprocess_maintenance_page(&$variables) {
  global $base_url;

  $theme_path = \Drupal::service('extension.path.resolver')->getPath('theme', 'koecontrato');
  $variables['theme_path'] = $base_url . '/' . $theme_path;

  if (!$variables['db_is_active']) {
    $variables['site_name'] = '';
  }
  $variables['#attached']['library'][] = 'koecontrato/maintenance-page';
}